sudo: false
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "nightly"
matrix:
  allow_failures:
    - python: nightly
install:
    - pip install -r requirements_dev.txt
before_script:
    flake8 .
script:
    - tox
after_success:
    coveralls
