sudo: false
language: python
env:
    - TOXENV=py2.6
    - TOXENV=py2.7
    - TOXENV=py3.3
    - TOXENV=py3.4
    - TOXENV=flake8
matrix:
  include:
    - python: 3.5
      env:
      - TOXENV=py35
install:
    - pip install flake8
    - pip install tox coveralls --use-mirrors
script:
    - tox
after_success:
    coveralls
